In [1]:
import datetime
import time

In [4]:
x=datetime.datetime.now()
#datetime
time.sleep(5)
print (x.year)
print (datetime.datetime.now())
print (time.ctime())

x

2019
2019-08-10 09:19:49.831261
Sat Aug 10 09:19:49 2019


datetime.datetime(2019, 8, 10, 9, 19, 44, 830795)

In [7]:
def module():
    x=datetime.datetime.now()
    #datetime
    time.sleep(5)
    print (x.year)
    print (datetime.datetime.now())
    print (time.ctime())

    x
    
    


In [8]:
module()

2019
2019-08-10 09:29:23.728329
Sat Aug 10 09:29:23 2019


In [11]:
print(time.ctime())

Sat Aug 10 09:43:27 2019


In [14]:
a=time.ctime()
a=a.split()
print (a)

['Sat', 'Aug', '10', '09:51:22', '2019']


In [16]:
print(a[3])

09:51:22


In [26]:
if a[3]=='09:59:60':
    print('hello')
    break

SyntaxError: 'break' outside loop (<ipython-input-26-459f851ab1d9>, line 6)

In [2]:
def abj():
    a=time.ctime()
    print(a[3])


In [4]:
abj()

In [6]:
a=30
b='hello'
txt='i am {} with the {} '

In [8]:
print(txt.format(a,b))

i am 30 with the hello 


In [1]:
import request

ModuleNotFoundError: No module named 'request'

In [1]:
import request

ModuleNotFoundError: No module named 'request'

In [13]:
pip install request

Note: you may need to restart the kernel to use updated packages.


'C:\Users\Abhishek' is not recognized as an internal or external command,
operable program or batch file.


In [14]:
import requests

In [15]:
from bs4 import BeautifulSoup

In [16]:
url='https://www.cricbuzz.com › cricket-match › live-scores'

In [17]:
requests.get('https://www.cricbuzz.com › cricket-match › live-scores')

InvalidURL: URL has an invalid label.

In [20]:
import requests

In [22]:
requests.get('https://www.cricbuzz.com/cricket')

<Response [404]>

In [23]:
r=requests.get('https://www.cricbuzz.com/cricket-match/live-scores')

In [33]:
r.text

'\r\n\r\n<!DOCTYPE html><html lang="en" itemscope itemtype="http://schema.org/WebPage"><head><meta charset="utf-8"><script>var is_mobile = /symbian|tizen|midp|uc(web|browser)|MSIE (5.0|6.0|7.0|8.0)|tablet/i.test(navigator.userAgent);\tif(is_mobile && window.location.hostname != "www1.cricbuzz.com") window.location.hostname = "m.cricbuzz.com";</script><style>body{background:#E3E6E3; font-family: helvetica,"Segoe UI",Arial,sans-serif;color:#222;font-size:14px; line-height: 1.5; margin:0;}\tbody, .cb-comm-pg, .cb-hm-mid {min-height:1000px}\t.container{width:980px;margin:0 auto;}\t.page{max-width: 980px;margin: 0 auto;position: relative;}\t.cb-col-8 {width:8%;}\t.cb-col-10 {width:10%;}\t.cb-col-14 {width:14%;}\t.cb-col-16 {width:16%;}\t.cb-col-20 {width:20%;}\t.cb-col-25 {width:25%;}\t.cb-col-27 {width:27%;}\t.cb-col-33 {width:33%;}\t.cb-col-40 {width:40%;}\t.cb-col-46 {width:46%;}\t.cb-col-47 {width:47%;}\t.cb-col-50 {width:50%;}\t.cb-col-60 {width:60%;}\t.cb-col-66 {width:66%;}\t.cb-col-

In [24]:
from bs4 import BeautifulSoup

In [25]:
s=  BeautifulSoup(r.content,'html5lib')

In [26]:
s

<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta charset="utf-8"/><script>var is_mobile = /symbian|tizen|midp|uc(web|browser)|MSIE (5.0|6.0|7.0|8.0)|tablet/i.test(navigator.userAgent);	if(is_mobile && window.location.hostname != "www1.cricbuzz.com") window.location.hostname = "m.cricbuzz.com";</script><style>body{background:#E3E6E3; font-family: helvetica,"Segoe UI",Arial,sans-serif;color:#222;font-size:14px; line-height: 1.5; margin:0;}	body, .cb-comm-pg, .cb-hm-mid {min-height:1000px}	.container{width:980px;margin:0 auto;}	.page{max-width: 980px;margin: 0 auto;position: relative;}	.cb-col-8 {width:8%;}	.cb-col-10 {width:10%;}	.cb-col-14 {width:14%;}	.cb-col-16 {width:16%;}	.cb-col-20 {width:20%;}	.cb-col-25 {width:25%;}	.cb-col-27 {width:27%;}	.cb-col-33 {width:33%;}	.cb-col-40 {width:40%;}	.cb-col-46 {width:46%;}	.cb-col-47 {width:47%;}	.cb-col-50 {width:50%;}	.cb-col-60 {width:60%;}	.cb-col-66 {width:66%;}	.cb-col-67 {width:67%;}	.cb-col

In [27]:
for i in s.find_all('div',{'class':'cb-col cb-col-100 cb-lv-main'}):
    print(i.text)

INDIA TOUR OF WEST INDIES, 2019West Indies vs India, 1st Test -  •  at Sir Vivian Richards Stadium, North Sound, Antigua   WI 189/8 (59.0 Ovs)  •  IND 297 Day 2: Stumps - West Indies trail by 108 runs      Live ScoreScorecardFull CommentaryNews
THE ASHES 2019England vs Australia, 3rd Test -  •  at Headingley, Leeds   AUS 179, 171/6 (57.0 Ovs)  •  ENG 67 Day 2: Stumps - Australia lead by 283 runs      Live ScoreScorecardFull CommentaryNews
NEW ZEALAND TOUR OF SRI LANKA, 2019Sri Lanka vs New Zealand, 2nd Test -  •  at P Sara Oval, Colombo   NZ 30/1 (11.5 Ovs)  •  SL 244 Day 3: 2nd Session - New Zealand trail by 214 runs      Live ScoreScorecardFull CommentaryNews
BOTSWANA TOUR OF NAMIBIA, 2019Namibia vs Botswana, 4th T20I •  at United Cricket Club Ground, Windhoek   NAM 86/2 (11.1 Ovs)  •  BW 85/8 (20.0 Ovs) Namibia won by 8 wkts      Live ScoreScorecardFull CommentaryNews
T20 BLAST 2019Kent vs Surrey, South Group •  at St Lawrence Ground, Canterbury   KENT 170/3 (20.0 Ovs)  •  SUR 171/7

In [28]:
f=open(Abhishek.txt,'w')

NameError: name 'Abhishek' is not defined

In [31]:
f=open("Abhishek.txt","a")
f.write(i.text)
f.close()

f=open("Abhishek.txt","r")
print(f.read())

Yorkshire Diamonds vs Lancashire Thunder, 23rd Match •  at North Marine Road Ground, Scarborough   YD 168/6 (18.5 Ovs)  •  LT 164/5 (20.0 Ovs) Yorkshire Diamonds won by 4 wkts      Live ScoreScorecardFull CommentaryNewsYorkshire Diamonds vs Lancashire Thunder, 23rd Match •  at North Marine Road Ground, Scarborough   YD 168/6 (18.5 Ovs)  •  LT 164/5 (20.0 Ovs) Yorkshire Diamonds won by 4 wkts      Live ScoreScorecardFull CommentaryNews


In [1]:
a="wdlld"
b='alalla'

In [3]:
print(b)

alalla


In [4]:
import numpy
import numpy as np

In [6]:
np.array([1,2,3])


array([1, 2, 3])

In [13]:
a=np.array(([1,1,1],[2,3,4]))

In [14]:
print(a)

[[1 1 1]
 [2 3 4]]


In [22]:
type(a)

numpy.ndarray

In [23]:
a.dtype

dtype('int32')

In [24]:
print(type(a))

<class 'numpy.ndarray'>


In [25]:
b=a.dtype

In [26]:
print(b)

int32


In [32]:
c=np.array([[1,2,3,4,5],[11,22,33,44,55],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [33]:
print(c)

[[ 1  2  3  4  5]
 [11 22 33 44 55]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]]


In [47]:
print(c[:3,1:5:2])

[[ 1  3  5]
 [11 33 55]
 [ 1  3  5]]


In [48]:
d=np.array([1,2,3])
e=np.array([1,2,3])

In [49]:
g=d+e

In [50]:
print(g)

[2 4 6]


In [55]:
p=[1,2,3]
q=[1,2,3]


In [59]:
g=np.array(p)

array([1, 2, 3])

In [64]:
h=np.array(q)

In [66]:
w=g*h

In [67]:
print(w)

[ 2  8 18]


In [72]:
np.arange(1,3,-4)

array([], dtype=int32)

In [73]:
np.datetime64

numpy.datetime64

In [120]:
n=np.datetime64('2019-12')

In [121]:
print(n)

2019-12


In [122]:
k=np.datetime64('2019-09')

In [123]:

np.arange(n,k,dtype='datetime64[M]')

array([], dtype='datetime64[M]')

In [7]:
import pandas as pd

In [11]:
a=['bhag','boss','dkdk','dk','bos']
b={'name','marks'}

In [12]:
pd.DataFrame(a)

0
0  bhag
1  boss
2  dkdk
3    dk
4   bos

In [13]:
pd.DataFrame(b)

0
0   name
1  marks

In [14]:
import numpy as np

In [18]:
b={'name':['raju','papu','ramu'],'marks':['1','2','3'],'roll.no.':['1','2','3'],'college':['asd','cgb','vnvn'],'religion':['ind','ind','ind']}


In [21]:
a=pd.DataFrame(b)

In [23]:
print(a[0:2])

   name marks roll.no. college religion
0  raju     1        1     asd      ind
1  papu     2        2     cgb      ind


In [24]:
import numpy as np

In [28]:
t={'name':['raju','papu','ramu'],'class':['12',np.nan,'11'],'rollno':['1','2','3']}

In [29]:
pd.DataFrame(t)

name class rollno
0  raju    12      1
1  papu   NaN      2
2  ramu    11      3

In [30]:
x=pd.DataFrame(t)

In [31]:
x.fillna(0)

name class rollno
0  raju    12      1
1  papu     0      2
2  ramu    11      3

In [33]:
x.dropna()

name class rollno
0  raju    12      1
2  ramu    11      3

In [3]:
import pandas as pd

In [4]:
pd.read_csv("FL_insurance_sample.csv")

policyID statecode           county  eq_site_limit  hu_site_limit  \
0        119736        FL      CLAY COUNTY       498960.0      498960.00   
1        448094        FL      CLAY COUNTY      1322376.3     1322376.30   
2        206893        FL      CLAY COUNTY       190724.4      190724.40   
3        333743        FL      CLAY COUNTY            0.0       79520.76   
4        172534        FL      CLAY COUNTY            0.0      254281.50   
5        785275        FL      CLAY COUNTY            0.0      515035.62   
6        995932        FL      CLAY COUNTY            0.0    19260000.00   
7        223488        FL      CLAY COUNTY       328500.0      328500.00   
8        433512        FL      CLAY COUNTY       315000.0      315000.00   
9        142071        FL      CLAY COUNTY       705600.0      705600.00   
10       253816        FL      CLAY COUNTY       831498.3      831498.30   
11       894922        FL      CLAY COUNTY            0.0       24059.09   
12       422834        FL      CLAY COUNTY            0.0       48115.94   
13       582721        FL      CLAY COUNTY            0.0       28869.12   
14       842700        FL      CLAY COUNTY            0.0       56135.64   
15       874333        FL      CLAY COUNTY            0.0       48115.94   
16       580146        FL      CLAY COUNTY            0.0       48115.94   
17       456149        FL      CLAY COUNTY            0.0       80192.49   
18       767862        FL      CLAY COUNTY            0.0       48115.94   
19       353022        FL      CLAY COUNTY            0.0       60946.79   
20       367814        FL      CLAY COUNTY            0.0       28869.12   
21       671392        FL      CLAY COUNTY            0.0    13410000.00   
22       772887        FL      CLAY COUNTY            0.0     1669113.93   
23       983122        FL      CLAY COUNTY            0.0      179562.23   
24       934215        FL      CLAY COUNTY            0.0      177744.16   
25       385951        FL      CLAY COUNTY            0.0       17757.58   
26       716332        FL      CLAY COUNTY            0.0      130129.87   
27       751262        FL      CLAY COUNTY            0.0       42854.77   
28       633663        FL      CLAY COUNTY            0.0         785.58   
29       105851        FL      CLAY COUNTY            0.0      170361.91   
...         ...       ...              ...            ...            ...   
36604    792963        FL  PINELLAS COUNTY            0.0      492483.92   
36605    367030        FL  PINELLAS COUNTY            0.0      954000.00   
36606    594660        FL  PINELLAS COUNTY            0.0      900000.00   
36607    360785        FL  PINELLAS COUNTY            0.0     1093500.00   
36608    847570        FL  PINELLAS COUNTY            0.0      436632.30   
36609    196088        FL  PINELLAS COUNTY      1917403.2     1917403.20   
36610    166064        FL  PINELLAS COUNTY      1392346.8     1392346.80   
36611    507269        FL  PINELLAS COUNTY      1175310.0     1175310.00   
36612    335445        FL  PINELLAS COUNTY        47250.9       47250.90   
36613    451921        FL  PINELLAS COUNTY        18630.0       18630.00   
36614    859202        FL  PINELLAS COUNTY         9450.0        9450.00   
36615    584224        FL  PINELLAS COUNTY            0.0      866904.30   
36616    603769        FL  PINELLAS COUNTY            0.0     1541972.70   
36617    575194        FL  PINELLAS COUNTY            0.0     3759303.60   
36618    708726        FL  PINELLAS COUNTY            0.0      717846.30   
36619    645213        FL  PINELLAS COUNTY            0.0     1728847.80   
36620    175829        FL  PINELLAS COUNTY            0.0    24210000.00   
36621    546178        FL  PINELLAS COUNTY            0.0     1331880.30   
36622    938910        FL  PINELLAS COUNTY            0.0       35408.70   
36623    592170        FL  PINELLAS COUNTY            0.0       24574.50   
36624    827844        FL  PINELLAS COUNTY            0

In [1]:
w=pd.read_csv("FL_insurance_sample.csv")

NameError: name 'pd' is not defined

In [2]:
w.head()

NameError: name 'w' is not defined

In [8]:
w.tail()

policyID statecode           county  eq_site_limit  hu_site_limit  \
36629    404309        FL  PINELLAS COUNTY            0.0        88722.0   
36630    465875        FL  PINELLAS COUNTY      1297057.5      1297057.5   
36631    791209        FL  PINELLAS COUNTY       173286.9       173286.9   
36632    322627        FL  PINELLAS COUNTY      1499781.6      1499781.6   
36633    398149        FL  PINELLAS COUNTY       373488.3       373488.3   

       fl_site_limit  fr_site_limit   tiv_2011    tiv_2012  \
36629            0.0        88722.0    88722.0   155065.65   
36630      1297057.5      1297057.5  1297057.5  1577500.79   
36631            0.0            0.0   173286.9   205527.97   
36632            0.0            0.0  1499781.6  1768782.43   
36633            0.0            0.0   373488.3   596003.67   

       eq_site_deductible  hu_site_deductible  fl_site_deductible  \
36629                 0.0                 0.0                 0.0   
36630                 0.0                 0.0                 0.0   
36631                 0.0                 0.0                 0.0   
36632                 0.0                 0.0                 0.0   
36633                 0.0                 0.0                 0.0   

       fr_site_deductible  point_latitude  point_longitude         line  \
36629                   0       28.122885       -82.770218  Residential   
36630                   0       28.080900       -82.758800  Residential   
36631                   0       28.110550       -82.766360  Residential   
36632                   0       28.089415       -82.697411  Residential   
36633                   0       28.064440       -82.774590  Residential   

      construction  point_granularity  
36629         Wood                  3  
36630      Masonry                  1  
36631         Wood                  4  
36632      Masonry                  3  
36633      Masonry                  1

In [10]:
pd.DataFrame(w[['statecode','policyID']])

statecode  policyID
0            FL    119736
1            FL    448094
2            FL    206893
3            FL    333743
4            FL    172534
5            FL    785275
6            FL    995932
7            FL    223488
8            FL    433512
9            FL    142071
10           FL    253816
11           FL    894922
12           FL    422834
13           FL    582721
14           FL    842700
15           FL    874333
16           FL    580146
17           FL    456149
18           FL    767862
19           FL    353022
20           FL    367814
21           FL    671392
22           FL    772887
23           FL    983122
24           FL    934215
25           FL    385951
26           FL    716332
27           FL    751262
28           FL    633663
29           FL    105851
...         ...       ...
36604        FL    792963
36605        FL    367030
36606        FL    594660
36607        FL    360785
36608        FL    847570
36609        FL    196088
36610        FL    166064
36611        FL    507269
36612        FL    335445
36613        FL    451921
36614        FL    859202
36615        FL    584224
36616        FL    603769
36617        FL    575194
36618        FL    708726
36619        FL    645213
36620        FL    175829
36621        FL    546178
36622        FL    938910
36623        FL    592170
36624        FL    827844
36625        FL    876385
36626        FL    167630
36627        FL    241496
36628        FL    780814
36629        FL    404309
36630        FL    465875
36631        FL    791209
36632        FL    322627
36633        FL    398149

[36634 rows x 2 columns]

In [14]:
j=pd.DataFrame(w[['statecode','policyID']],index=["county","dkdk"])

In [15]:
j

statecode  policyID
county       NaN       NaN
dkdk         NaN       NaN